#!/usr/bin/env python3
"""
Generate (user_turn, retrieval_hint) training pairs for fine-tuning chitta-hint.

Sources:
  1. Real session transcripts from ~/.claude/projects/
  2. Synthetic diverse examples covering all personal fact types

Labels generated by gemma4:26b via local Ollama.
Output: JSONL with {"instruction", "input", "output"} fields (Alpaca format).

Usage:
    python3 generate_hint_training_data.py \
        --out /maps/projects/caeg/scratch/kbd606/tmp/hint_train.jsonl \
        [--model gemma4:26b] [--max N]
"""

import argparse
import glob
import json
import os
import sys
import time
import urllib.request

DEFAULT_MODEL = "llama3.2:3b"   # instruct model, fast, reliable for this task
OLLAMA_URL = "http://localhost:11434"
LLM_TIMEOUT = 30

INSTRUCTION = (
    "Rewrite the following user statement as a short third-person retrieval fact "
    "starting with 'User' (8-15 words). Output only the fact, no explanation. "
    "If there is no personal fact, output exactly: -"
)

# Diverse synthetic user turns covering all personal-fact types
SYNTHETIC_TURNS = [
    # name
    "My name is Sarah Chen, but everyone calls me Sara.",
    "I go by Alex. My full name is Alexander Novak.",
    "Call me Priya.",
    # education
    "I graduated with a Bachelor of Science in Computer Science last June.",
    "I just finished my PhD in molecular biology.",
    "I'm currently doing my Master's in data science at DTU.",
    "I have a degree in economics from Copenhagen University.",
    "I dropped out of college after two years to start my company.",
    "I got my B.Sc. last spring.",
    # occupation
    "I work as a software engineer at a biotech startup.",
    "I'm a nurse practitioner at Rigshospitalet.",
    "I'm self-employed — I run a small consulting firm.",
    "I used to be a teacher but now I'm in sales.",
    "I just got promoted to senior researcher.",
    "I'm a postdoc in the bioinformatics group.",
    "I'm currently between jobs.",
    # location
    "I live in Copenhagen, near Nørreport station.",
    "I moved to Aarhus from Stockholm last year.",
    "I'm originally from Lagos but I've been in Denmark for five years.",
    "I grew up in a small town in rural Germany.",
    "My hometown is Bangalore, though I live in Berlin now.",
    "I'm based in San Francisco for work.",
    # family
    "I have two kids, a boy and a girl, ages 4 and 7.",
    "I'm married and we just had our first child.",
    "I live with my partner of eight years.",
    "I'm single, no kids.",
    "My mom was a doctor and my dad was a teacher.",
    "I have a twin sister.",
    # preferences food
    "I'm vegetarian, have been for about ten years.",
    "I love Thai food, especially pad see ew.",
    "I'm allergic to nuts so I have to be careful.",
    "I don't drink coffee — strictly a tea person.",
    "I've been vegan for two years now.",
    # preferences drink
    "I drink about three cups of coffee a day.",
    "I prefer green tea over coffee.",
    "I barely drink alcohol — maybe wine at dinner occasionally.",
    # preferences music
    "I'm really into jazz, Miles Davis especially.",
    "I mostly listen to podcasts, not much music.",
    "I play guitar in a band on weekends.",
    "I grew up listening to classical music.",
    # preferences sport / hobby
    "I run marathons — I've done four so far.",
    "I play chess competitively, rated around 1900.",
    "I do crossfit three times a week.",
    "My hobby is birdwatching, I keep a life list.",
    "I've been learning to sail this summer.",
    "I spend most of my free time reading.",
    "I love hiking — I try to do a big trail every summer.",
    "I started pottery classes six months ago.",
    "I paint watercolors on weekends.",
    # possessions
    "I just bought a new laptop — a ThinkPad X1.",
    "I drive a 2019 Volkswagen Golf.",
    "I finally got a standing desk for my home office.",
    # achievements
    "I published my first paper in Nature last month.",
    "I won a regional cooking competition last year.",
    "I got my PMP certification in January.",
    "I'm a licensed architect.",
    "I just passed the bar exam.",
    # health
    "I have type 1 diabetes, diagnosed when I was 12.",
    "I'm recovering from knee surgery.",
    "I started therapy about six months ago and it's really helped.",
    # travel
    "I've been to 34 countries so far.",
    "I lived in Japan for two years teaching English.",
    "I'm planning to move to Portugal next year.",
    # finances
    "I own my apartment.",
    "I'm renting for now while I figure out next steps.",
    # language
    "I speak Danish, English, and some French.",
    "I'm learning Mandarin, about B1 level.",
    # mixed / subtle
    "I have a morning routine — gym at 6, then work by 8.",
    "I work from home most days but go into the office on Thursdays.",
    "I've been sober for three years.",
    "I meditate every morning, about 20 minutes.",
    "My commute is brutal — 90 minutes each way.",
    "I switched careers at 35 and I don't regret it.",
    "I've been freelancing for about four years.",
    "I got diagnosed with ADHD as an adult last year.",
    "I'm an early bird — I'm up by 5:30 every day.",
    "I'm terrible at cooking, my partner does all of it.",
    "I've never owned a car.",
    "I volunteer at a food bank on Saturdays.",
    "I'm a night owl, I do my best work after midnight.",
    "I just moved into my first place alone.",
    # edge cases — no personal fact
    "I wonder if that function should be memoized.",
    "The build is still failing on CI.",
    "Can you help me debug this segfault?",
    "What time is it in Tokyo right now?",
    "Let's continue from where we left off yesterday.",
]


def discover_ollama() -> str:
    import glob as _glob
    for path in _glob.glob("/tmp/ollama-server-*.url"):
        try:
            url = open(path).read().strip()
            with urllib.request.urlopen(f"{url}/v1/models", timeout=3):
                return url
        except Exception:
            continue
    try:
        with urllib.request.urlopen(f"{OLLAMA_URL}/v1/models", timeout=3):
            return OLLAMA_URL
    except Exception:
        return ""


def label(endpoint: str, model: str, text: str) -> str:
    prompt = f'{INSTRUCTION}\n\nStatement: "{text}"\n\nFact:'
    body = json.dumps({
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.1, "num_predict": 48},
    }).encode()
    req = urllib.request.Request(
        f"{endpoint}/api/generate",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=LLM_TIMEOUT) as r:
            resp = json.loads(r.read())
        hint = resp.get("response", "").strip()
        # Trim to first sentence
        for sep in (".\n", "\n", "."):
            idx = hint.find(sep)
            if 5 < idx < 120:
                hint = hint[:idx + 1].strip()
                break
        return hint[:150]
    except Exception as e:
        sys.stderr.write(f"[gen] label failed: {e}\n")
        return ""


def collect_real_turns() -> list[str]:
    projects = os.path.expanduser("~/.claude/projects")
    turns = []
    for jsonl in sorted(glob.glob(f"{projects}/**/*.jsonl", recursive=True))[:100]:
        try:
            for line in open(jsonl):
                rec = json.loads(line)
                msg = rec.get("message", {})
                if msg.get("role") != "user":
                    continue
                content = msg.get("content", "")
                if isinstance(content, list):
                    parts = [c.get("text", "") for c in content
                             if isinstance(c, dict) and c.get("type") == "text"]
                    content = " ".join(parts)
                content = str(content).strip()
                if len(content) < 15 or len(content) > 400:
                    continue
                low = content.lower()
                if not any(w in low for w in [" i ", "i'm", "i've", "i am", "my ", "i have", "i got", "i live", "i work", "i study"]):
                    continue
                if content.startswith(("<", "{", "/")):
                    continue
                if any(kw in low for kw in ["task-notification", "system-reminder", "tool_use"]):
                    continue
                turns.append(content)
        except Exception:
            continue
    seen = set()
    unique = []
    for t in turns:
        k = t[:60]
        if k not in seen:
            seen.add(k)
            unique.append(t)
    return unique[:500]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="/maps/projects/caeg/scratch/kbd606/tmp/hint_train.jsonl")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--max", type=int, default=2000)
    args = parser.parse_args()

    endpoint = discover_ollama()
    if not endpoint:
        sys.exit("[gen] no Ollama endpoint")

    # Combine real + synthetic
    real = collect_real_turns()
    all_turns = real + SYNTHETIC_TURNS
    # Deduplicate
    seen = set()
    unique = []
    for t in all_turns:
        k = t[:60]
        if k not in seen:
            seen.add(k)
            unique.append(t)
    unique = unique[: args.max]
    sys.stderr.write(f"[gen] {len(real)} real + {len(SYNTHETIC_TURNS)} synthetic = {len(unique)} unique turns\n")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    written = 0
    with open(args.out, "w") as f:
        for i, turn in enumerate(unique):
            hint = label(endpoint, args.model, turn)
            if not hint:
                sys.stderr.write(f"[gen] [{i+1}/{len(unique)}] skip (empty)\n")
                continue
            record = {
                "instruction": INSTRUCTION,
                "input": turn,
                "output": hint,
            }
            f.write(json.dumps(record) + "\n")
            f.flush()
            written += 1
            sys.stderr.write(f"[gen] [{i+1}/{len(unique)}] {turn[:50]!r} → {hint!r}\n")

    print(f"Wrote {written} training pairs to {args.out}")


if __name__ == "__main__":
    main()
