#!/bin/bash
# ralph.sh - Memory-powered autonomous development loop
#
# Usage: ralph.sh [command] [args]
# Commands:
#   init [goal]    Initialize new Ralph task
#   status         Show current task status
#   loop           Run one iteration of the loop
#   pause          Pause and checkpoint
#   resume         Resume from checkpoint
#   complete       Mark task as complete

set -e

# Configuration
RALPH_DIR=".ralph"
FIX_PLAN="$RALPH_DIR/fix_plan.md"
AGENT_MD="$RALPH_DIR/AGENT.md"
SPECS_DIR="$RALPH_DIR/specs"
RALPHRC=".ralphrc"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Get chitta binary
CHITTA="${CHITTA_BIN:-chitta}"

# Load config if exists
if [[ -f "$RALPHRC" ]]; then
    source "$RALPHRC"
fi

MAX_LOOPS="${MAX_LOOPS:-50}"
CONFIRM_INTERVAL="${CONFIRM_INTERVAL:-5}"
AUTO_COMMIT="${AUTO_COMMIT:-false}"

# Get project name from git or directory
get_project_name() {
    local name
    name=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null)
    if [[ -z "$name" ]]; then
        name=$(basename "$(pwd)")
    fi
    echo "$name"
}

# Generate task ID
generate_task_id() {
    local project=$(get_project_name)
    local timestamp=$(date +%s)
    echo "ralph-${project}-${timestamp}"
}

# Log with color
log() {
    local level=$1
    shift
    local msg="$*"
    local color=$NC

    case $level in
        INFO)  color=$BLUE ;;
        WARN)  color=$YELLOW ;;
        ERROR) color=$RED ;;
        OK)    color=$GREEN ;;
        TASK)  color=$CYAN ;;
    esac

    echo -e "${color}[$level]${NC} $msg"
}

# Recall relevant memories for this project
recall_context() {
    local project=$(get_project_name)
    log INFO "Recalling context for project: $project"

    # Recall project-specific memories
    $CHITTA recall --query "$project decisions solutions gotchas patterns" --limit 10 2>/dev/null || true

    # Check for active long task
    local active_task
    active_task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -n "$active_task" && "$active_task" != "null" ]]; then
        log INFO "Found active task, getting snapshot..."
        $CHITTA long_task_snapshot --task_id "$active_task" --mode brief 2>/dev/null || true
    fi
}

# Initialize Ralph task
cmd_init() {
    local goal="$1"

    if [[ -z "$goal" ]]; then
        echo -n "What's the goal? "
        read -r goal
    fi

    if [[ -z "$goal" ]]; then
        log ERROR "Goal is required"
        exit 1
    fi

    # Create .ralph directory structure
    mkdir -p "$RALPH_DIR" "$SPECS_DIR"

    # Create fix_plan.md if not exists
    if [[ ! -f "$FIX_PLAN" ]]; then
        cat > "$FIX_PLAN" << EOF
# Fix Plan

## Goal
$goal

## Priority 1 - Critical
- [ ] Define requirements and architecture
- [ ] Set up project structure

## Priority 2 - Important
- [ ] Implement core functionality
- [ ] Add tests

## Priority 3 - Nice to Have
- [ ] Documentation
- [ ] Polish and optimization

---
*Auto-generated by Ralph. Edit as needed.*
EOF
        log OK "Created $FIX_PLAN"
    fi

    # Create AGENT.md if not exists
    if [[ ! -f "$AGENT_MD" ]]; then
        cat > "$AGENT_MD" << EOF
# Agent Instructions

## Build
\`\`\`bash
# Add build commands here
\`\`\`

## Run
\`\`\`bash
# Add run commands here
\`\`\`

## Test
\`\`\`bash
# Add test commands here
\`\`\`
EOF
        log OK "Created $AGENT_MD"
    fi

    # Start long task
    local task_id=$(generate_task_id)
    local project=$(get_project_name)

    log INFO "Starting long task: $task_id"
    $CHITTA long_task_start \
        --task_id "$task_id" \
        --goal "$goal" \
        --realm "$project" 2>/dev/null || true

    # Store to memory
    $CHITTA remember --content "[ralph] task:$task_id→started @$project
goal: $goal
fix_plan: $FIX_PLAN" 2>/dev/null || true

    log OK "Ralph initialized for: $goal"
    log INFO "Fix plan: $FIX_PLAN"
    log INFO "Task ID: $task_id"

    echo ""
    echo "Run '/ralph' or 'ralph.sh loop' to start working"
}

# Show status
cmd_status() {
    local project=$(get_project_name)

    echo -e "${CYAN}═══════════════════════════════════════${NC}"
    echo -e "${CYAN}  Ralph Status: $project${NC}"
    echo -e "${CYAN}═══════════════════════════════════════${NC}"

    # Check for active task
    local active_task
    active_task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -n "$active_task" && "$active_task" != "null" ]]; then
        echo ""
        echo -e "${GREEN}Active Task:${NC} $active_task"
        echo ""
        $CHITTA long_task_snapshot --task_id "$active_task" --mode brief 2>/dev/null || true
    else
        echo ""
        echo -e "${YELLOW}No active task${NC}"
        echo "Run '/ralph init' to start"
    fi

    # Show fix_plan status
    if [[ -f "$FIX_PLAN" ]]; then
        echo ""
        echo -e "${BLUE}Fix Plan Progress:${NC}"
        local total=$(grep -cE "^\s*- \[" "$FIX_PLAN" 2>/dev/null || echo "0")
        local done=$(grep -cE "^\s*- \[x\]" "$FIX_PLAN" 2>/dev/null || echo "0")
        echo "  $done/$total items complete"

        echo ""
        echo -e "${YELLOW}Next tasks:${NC}"
        grep -E "^\s*- \[ \]" "$FIX_PLAN" 2>/dev/null | head -3 | sed 's/^/  /'
    fi

    # Recent memories
    echo ""
    echo -e "${BLUE}Recent Learnings:${NC}"
    $CHITTA recall --query "$project solution gotcha decision" --limit 3 2>/dev/null | head -10 || true
}

# Run one loop iteration
cmd_loop() {
    local iteration=${1:-1}
    local project=$(get_project_name)

    log TASK "═══ Loop #$iteration ═══"

    # 1. Recall context
    log INFO "Phase 1: Recall context"
    recall_context

    # 2. Check fix_plan for next task
    log INFO "Phase 2: Check fix_plan.md"
    if [[ ! -f "$FIX_PLAN" ]]; then
        log ERROR "No fix_plan.md found. Run '/ralph init' first."
        exit 1
    fi

    local next_task
    next_task=$(grep -m1 -E "^\s*- \[ \]" "$FIX_PLAN" 2>/dev/null | sed 's/.*\[ \]//' | xargs)

    if [[ -z "$next_task" ]]; then
        log OK "All tasks complete!"
        return 0
    fi

    log TASK "Next task: $next_task"

    # 3. Build prompt with context
    local prompt="You are working on: $project

## Current Task
$next_task

## Context
$(cat "$FIX_PLAN")

## Instructions
1. Work on the current task only
2. Mark it [x] in fix_plan.md when complete
3. Use [SOLUTION], [GOTCHA], [DECISION] markers for learnings
4. End with RALPH_STATUS block

## RALPH_STATUS Format
\`\`\`
---RALPH_STATUS---
STATUS: IN_PROGRESS | COMPLETE | BLOCKED
TASKS_COMPLETED_THIS_LOOP: <number>
FILES_MODIFIED: <number>
TESTS_STATUS: PASSING | FAILING | NOT_RUN
WORK_TYPE: IMPLEMENTATION | TESTING | DOCUMENTATION
EXIT_SIGNAL: false | true
RECOMMENDATION: <what to do next>
---END_RALPH_STATUS---
\`\`\`"

    # Output prompt for Claude to process
    echo ""
    echo "=========================================="
    echo "RALPH LOOP PROMPT (iteration $iteration)"
    echo "=========================================="
    echo "$prompt"
    echo "=========================================="

    # 4. Update long task
    local active_task
    active_task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -n "$active_task" && "$active_task" != "null" ]]; then
        $CHITTA long_task_event \
            --task_id "$active_task" \
            --event_type checkpoint \
            --description "Loop $iteration: Working on '$next_task'" 2>/dev/null || true
    fi

    return 1  # Continue looping
}

# Pause and checkpoint
cmd_pause() {
    local project=$(get_project_name)

    log INFO "Pausing Ralph loop..."

    local active_task
    active_task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -n "$active_task" && "$active_task" != "null" ]]; then
        $CHITTA long_task_event \
            --task_id "$active_task" \
            --event_type checkpoint \
            --description "User requested pause" 2>/dev/null || true

        # Store checkpoint to memory
        $CHITTA remember --content "[ralph] $project→paused @$(date -Iseconds)
task: $active_task
reason: user_pause" 2>/dev/null || true
    fi

    log OK "Paused. Run '/ralph resume' to continue."
}

# Resume from checkpoint
cmd_resume() {
    local project=$(get_project_name)

    log INFO "Resuming Ralph loop..."

    # Recall checkpoint
    $CHITTA recall --query "$project ralph paused checkpoint" --limit 3 2>/dev/null || true

    local active_task
    active_task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -n "$active_task" && "$active_task" != "null" ]]; then
        log INFO "Found active task: $active_task"
        $CHITTA long_task_snapshot --task_id "$active_task" --mode brief 2>/dev/null || true

        $CHITTA long_task_event \
            --task_id "$active_task" \
            --event_type checkpoint \
            --description "Resumed from pause" 2>/dev/null || true
    else
        log WARN "No active task found. Run '/ralph init' to start."
    fi
}

# Complete task
cmd_complete() {
    local outcome="$1"
    local project=$(get_project_name)

    if [[ -z "$outcome" ]]; then
        echo -n "Outcome summary: "
        read -r outcome
    fi

    local active_task
    active_task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -z "$active_task" || "$active_task" == "null" ]]; then
        log WARN "No active task to complete"
        return 1
    fi

    log INFO "Completing task: $active_task"

    # Complete long task
    $CHITTA long_task_complete \
        --task_id "$active_task" \
        --outcome "$outcome" 2>/dev/null || true

    # Store to memory
    $CHITTA remember --content "[ralph] $project→completed @$(date -Iseconds)
task: $active_task
outcome: $outcome" 2>/dev/null || true

    # Store learnings
    $CHITTA learn_milestone \
        --milestone "Completed Ralph task for $project" \
        --details "$outcome" 2>/dev/null || true

    log OK "Task completed: $outcome"
}

# Parse command
case "${1:-}" in
    init)
        shift
        cmd_init "$*"
        ;;
    status)
        cmd_status
        ;;
    loop)
        shift
        cmd_loop "${1:-1}"
        ;;
    pause)
        cmd_pause
        ;;
    resume)
        cmd_resume
        ;;
    complete)
        shift
        cmd_complete "$*"
        ;;
    help|--help|-h)
        echo "ralph.sh - Memory-powered autonomous development loop"
        echo ""
        echo "Usage: ralph.sh [command] [args]"
        echo ""
        echo "Commands:"
        echo "  init [goal]    Initialize new Ralph task"
        echo "  status         Show current task status"
        echo "  loop [n]       Run loop iteration n"
        echo "  pause          Pause and checkpoint"
        echo "  resume         Resume from checkpoint"
        echo "  complete [msg] Mark task as complete"
        echo ""
        echo "Configuration (.ralphrc):"
        echo "  MAX_LOOPS=50           Max iterations"
        echo "  CONFIRM_INTERVAL=5     Confirm every N loops"
        echo "  AUTO_COMMIT=false      Auto-commit after loops"
        ;;
    *)
        # Default: show status or start loop
        if [[ -f "$FIX_PLAN" ]]; then
            cmd_status
        else
            echo "No Ralph task found in this directory."
            echo "Run 'ralph.sh init \"your goal\"' to start."
        fi
        ;;
esac
