#!/bin/bash
# yajna.sh - Autonomous development ritual
#
# CLI helper for /yajna skill. The skill runs autonomously within Claude Code.
# Use this script for:
#   - Initializing rituals from CLI
#   - Checking status externally
#   - CI/CD integration
#
# Usage: yajna.sh [command] [args]

set -e

YAJNA_DIR=".yajna"
FIX_PLAN="$YAJNA_DIR/fix_plan.md"
CHITTA="${CHITTA_BIN:-chitta}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

[[ -f ".yajnarc" ]] && source ".yajnarc"
MAX_LOOPS="${MAX_LOOPS:-50}"

log() {
    local level=$1; shift
    local color=$NC
    case $level in
        INFO)  color=$BLUE ;;
        WARN)  color=$YELLOW ;;
        ERROR) color=$RED ;;
        OK)    color=$GREEN ;;
    esac
    echo -e "${color}[$level]${NC} $*"
}

get_project_name() {
    basename "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
}

cmd_status() {
    local project=$(get_project_name)

    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║  YAJÑA STATUS: $project${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"

    local task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -n "$task" && "$task" != "null" ]]; then
        echo -e "\n${GREEN}Active Ritual:${NC} $task"
        $CHITTA long_task_snapshot --task_id "$task" --mode brief 2>/dev/null || true
    else
        echo -e "\n${YELLOW}No active ritual${NC}"
        echo "Run '/yajna' or 'yajna.sh init' to start"
    fi

    if [[ -f "$FIX_PLAN" ]]; then
        echo -e "\n${BLUE}Fix Plan:${NC}"
        local total=$(grep -cE "^\s*- \[" "$FIX_PLAN" 2>/dev/null || echo "0")
        local done=$(grep -cE "^\s*- \[x\]" "$FIX_PLAN" 2>/dev/null || echo "0")
        echo "  Progress: $done/$total tasks"

        echo -e "\n${YELLOW}Remaining:${NC}"
        grep -E "^\s*- \[ \]" "$FIX_PLAN" 2>/dev/null | head -5 | sed 's/^/  /'
    fi

    echo -e "\n${BLUE}Recent Learnings:${NC}"
    $CHITTA recall --query "$project solution gotcha yajna" --limit 3 2>/dev/null | head -10 || true
}

cmd_init() {
    local goal="$1"

    if [[ -z "$goal" ]]; then
        echo -n "Goal: "
        read -r goal
    fi

    [[ -z "$goal" ]] && { log ERROR "Goal required"; exit 1; }

    mkdir -p "$YAJNA_DIR/specs"

    if [[ ! -f "$FIX_PLAN" ]]; then
        cat > "$FIX_PLAN" << EOF
# Yajña: $goal

## Priority 1 - Critical
- [ ] Analyze requirements
- [ ] Set up structure

## Priority 2 - Important
- [ ] Implement core functionality
- [ ] Add tests

## Priority 3 - Nice to Have
- [ ] Documentation
- [ ] Polish

---
*Generated by Yajña. Edit as needed.*
EOF
        log OK "Created $FIX_PLAN"
    fi

    local project=$(get_project_name)
    local task_id="yajna-${project}-$(date +%s)"

    log INFO "Starting ritual: $task_id"
    $CHITTA long_task_start \
        --task_id "$task_id" \
        --goal "$goal" \
        --realm "$project" 2>/dev/null || true

    $CHITTA remember --content "[yajña] ${project}→initialized
goal: $goal
task: $task_id" 2>/dev/null || true

    log OK "Yajña initialized: $goal"
    log INFO "Run '/yajna' in Claude Code to start"
}

cmd_pause() {
    local project=$(get_project_name)
    local task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    if [[ -n "$task" && "$task" != "null" ]]; then
        $CHITTA long_task_event \
            --task_id "$task" \
            --event_type checkpoint \
            --description "Paused via CLI" 2>/dev/null || true

        $CHITTA remember --content "[yajña] ${project}→paused
reason: cli_pause" 2>/dev/null || true

        log OK "Ritual paused. Run '/yajna' to resume."
    else
        log WARN "No active ritual"
    fi
}

cmd_complete() {
    local outcome="$1"
    local project=$(get_project_name)
    local task=$($CHITTA long_task_active --realm "$project" 2>/dev/null || echo "")

    [[ -z "$task" || "$task" == "null" ]] && { log WARN "No active ritual"; exit 1; }

    if [[ -z "$outcome" ]]; then
        echo -n "Outcome: "
        read -r outcome
    fi

    $CHITTA long_task_complete \
        --task_id "$task" \
        --outcome "$outcome" 2>/dev/null || true

    $CHITTA remember --content "[yajña] ${project}→completed
outcome: $outcome" 2>/dev/null || true

    log OK "Pūrṇāhuti: $outcome"
}

case "${1:-}" in
    init)
        shift
        cmd_init "$*"
        ;;
    status)
        cmd_status
        ;;
    pause)
        cmd_pause
        ;;
    complete)
        shift
        cmd_complete "$*"
        ;;
    help|--help|-h)
        cat << 'EOF'
yajna.sh - Autonomous development ritual

Usage: yajna.sh [command] [args]

Commands:
  (default)      Show status
  init [goal]    Initialize new ritual
  status         Show current status
  pause          Pause the ritual
  complete [msg] Mark ritual complete (pūrṇāhuti)

The /yajna skill runs autonomously in Claude Code.
This script is for CLI convenience and CI/CD.

Configuration (.yajnarc):
  MAX_LOOPS=50
  SKIP_TESTS=false
  PARALLEL_TASKS=true
EOF
        ;;
    *)
        cmd_status
        ;;
esac
