#!/usr/bin/env python3
"""
Sync static tool definitions from chittad daemon.

Usage:
    chitta-mcp-sync    # Regenerate tools_static.py from daemon
"""

import os
import sys
import json
import socket
from pathlib import Path


def djb2_hash(s: str) -> int:
    """DJB2 hash algorithm matching C++ implementation."""
    h = 5381
    for c in s:
        h = ((h << 5) + h + ord(c)) & 0xFFFFFFFF
    return h


def get_socket_dir() -> str:
    """Get persistent socket directory (matches C++ daemon logic)."""
    xdg_runtime = os.environ.get("XDG_RUNTIME_DIR")
    if xdg_runtime and os.access(xdg_runtime, os.W_OK):
        socket_dir = os.path.join(xdg_runtime, "chitta")
        os.makedirs(socket_dir, mode=0o700, exist_ok=True)
        return socket_dir
    run_user = f"/run/user/{os.getuid()}"
    if os.access(run_user, os.W_OK):
        socket_dir = os.path.join(run_user, "chitta")
        os.makedirs(socket_dir, mode=0o700, exist_ok=True)
        return socket_dir
    home = os.environ.get("HOME")
    if home:
        cache_dir = os.path.join(home, ".cache")
        os.makedirs(cache_dir, mode=0o755, exist_ok=True)
        socket_dir = os.path.join(cache_dir, "chitta")
        os.makedirs(socket_dir, mode=0o700, exist_ok=True)
        return socket_dir
    return "/tmp"


def get_socket_path() -> str:
    """Get the daemon socket path."""
    home = os.environ.get("HOME", "")
    mind_path = os.path.join(home, ".claude", "mind")  # Matches daemon's default
    hash_val = djb2_hash(mind_path)
    return os.path.join(get_socket_dir(), f"chitta-{hash_val}.sock")


def fetch_tools() -> list[dict]:
    """Fetch tools from daemon."""
    socket_path = get_socket_path()

    try:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.connect(socket_path)

        req = json.dumps({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/list",
            "params": {}
        }) + "\n"

        sock.sendall(req.encode())

        response = b""
        while True:
            chunk = sock.recv(4096)
            if not chunk:
                break
            response += chunk
            if b"\n" in response:
                break

        sock.close()

        data = json.loads(response.decode().strip())
        return data.get("result", {}).get("tools", [])

    except Exception as e:
        print(f"Error connecting to daemon: {e}", file=sys.stderr)
        return []


def strip_null_values(obj):
    """Recursively remove keys with null values from dicts."""
    if isinstance(obj, dict):
        return {k: strip_null_values(v) for k, v in obj.items() if v is not None}
    elif isinstance(obj, list):
        return [strip_null_values(item) for item in obj]
    return obj


def flex_integers(obj):
    """Replace type:integer with anyOf:[integer,string] so LLMs can pass "19" or 19.

    LLMs sometimes serialize integer arguments as JSON strings. Claude Code validates
    tool inputs against the schema before dispatch, so strict integer schemas cause
    'Input validation error' when the LLM generates a string. This makes schemas
    tolerant while server.py coerces the value back to int before forwarding.
    """
    if isinstance(obj, dict):
        if obj.get("type") == "integer":
            result = {k: v for k, v in obj.items() if k != "type"}
            result["anyOf"] = [{"type": "integer"}, {"type": "string"}]
            return result
        return {k: flex_integers(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [flex_integers(item) for item in obj]
    return obj


def generate_static_file(tools: list[dict]) -> str:
    """Generate Python code for static tools."""
    lines = [
        '#!/usr/bin/env python3',
        '"""',
        'Static tool definitions for chitta-mcp.',
        'Auto-generated by chitta-mcp-sync from daemon tools/list response.',
        '',
        'To regenerate: chitta-mcp-sync',
        '"""',
        '',
        'from mcp.types import Tool',
        '',
        'TOOLS = [',
    ]

    for t in tools:
        name = t["name"]
        desc = t["description"].replace('"', '\\"')
        # Strip null values from inputSchema (required: null breaks Zod validation)
        clean_schema = flex_integers(strip_null_values(t["inputSchema"]))
        # Fix null properties (should be empty object, not missing)
        if clean_schema.get("properties") is None:
            clean_schema["properties"] = {}
        schema = json.dumps(clean_schema, indent=8)
        # Convert JSON literals to Python
        schema = schema.replace(': true', ': True')
        schema = schema.replace(': false', ': False')
        # Indent the schema properly
        schema_lines = schema.split('\n')
        schema_formatted = schema_lines[0]
        for line in schema_lines[1:]:
            schema_formatted += '\n        ' + line

        lines.append(f'    Tool(')
        lines.append(f'        name="{name}",')
        lines.append(f'        description="{desc}",')
        lines.append(f'        inputSchema={schema_formatted}')
        lines.append(f'    ),')

    lines.append(']')
    lines.append('')

    return '\n'.join(lines)


def extract_composite_tools(filepath: Path) -> str:
    """Extract COMPOSITE_TOOLS section from existing file."""
    if not filepath.exists():
        return ""

    content = filepath.read_text()
    marker = "\nCOMPOSITE_TOOLS = ["
    idx = content.find(marker)
    if idx == -1:
        return ""

    return content[idx:]


def sync():
    """Sync tools from daemon and regenerate tools_static.py."""
    print("Fetching tools from daemon...")
    tools = fetch_tools()

    if not tools:
        print("No tools found. Is the daemon running?", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(tools)} tools")

    static_path = Path(__file__).parent / "tools_static.py"

    # Preserve COMPOSITE_TOOLS from existing file
    composite_section = extract_composite_tools(static_path)
    if composite_section:
        print("Preserving COMPOSITE_TOOLS section")

    # Generate the static file
    content = generate_static_file(tools)

    # Append COMPOSITE_TOOLS if it existed
    if composite_section:
        content += composite_section

    # Write to tools_static.py
    static_path.write_text(content)

    print(f"Written to {static_path}")
    print("Restart Claude Code to pick up new tools")


if __name__ == "__main__":
    sync()
