#!/usr/bin/env python3
"""
Sync static tool definitions from chittad daemon.

Usage:
    chitta-mcp-sync    # Regenerate tools_static.py from daemon
"""

import os
import sys
import json
import socket
from pathlib import Path


def djb2_hash(s: str) -> int:
    """DJB2 hash algorithm matching C++ implementation."""
    h = 5381
    for c in s:
        h = ((h << 5) + h + ord(c)) & 0xFFFFFFFF
    return h


def get_socket_path() -> str:
    """Get the daemon socket path."""
    home = os.environ.get("HOME", "")
    mind_path = os.path.join(home, ".claude", "mind", "chitta")
    hash_val = djb2_hash(mind_path)
    return f"/tmp/chitta-{hash_val}.sock"


def fetch_tools() -> list[dict]:
    """Fetch tools from daemon."""
    socket_path = get_socket_path()

    try:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.connect(socket_path)

        req = json.dumps({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/list",
            "params": {}
        }) + "\n"

        sock.sendall(req.encode())

        response = b""
        while True:
            chunk = sock.recv(4096)
            if not chunk:
                break
            response += chunk
            if b"\n" in response:
                break

        sock.close()

        data = json.loads(response.decode().strip())
        return data.get("result", {}).get("tools", [])

    except Exception as e:
        print(f"Error connecting to daemon: {e}", file=sys.stderr)
        return []


def generate_static_file(tools: list[dict]) -> str:
    """Generate Python code for static tools."""
    lines = [
        '#!/usr/bin/env python3',
        '"""',
        'Static tool definitions for chitta-mcp.',
        'Auto-generated by chitta-mcp-sync from daemon tools/list response.',
        '',
        'To regenerate: chitta-mcp-sync',
        '"""',
        '',
        'from mcp.types import Tool',
        '',
        'TOOLS = [',
    ]

    for t in tools:
        name = t["name"]
        desc = t["description"].replace('"', '\\"')
        schema = json.dumps(t["inputSchema"], indent=8)
        # Convert JSON literals to Python
        schema = schema.replace(': true', ': True')
        schema = schema.replace(': false', ': False')
        # Fix null properties (invalid JSON Schema) - must be empty object
        schema = schema.replace('"properties": null', '"properties": {}')
        schema = schema.replace(': null', ': None')
        # Indent the schema properly
        schema_lines = schema.split('\n')
        schema_formatted = schema_lines[0]
        for line in schema_lines[1:]:
            schema_formatted += '\n        ' + line

        lines.append(f'    Tool(')
        lines.append(f'        name="{name}",')
        lines.append(f'        description="{desc}",')
        lines.append(f'        inputSchema={schema_formatted}')
        lines.append(f'    ),')

    lines.append(']')
    lines.append('')

    return '\n'.join(lines)


def sync():
    """Sync tools from daemon and regenerate tools_static.py."""
    print("Fetching tools from daemon...")
    tools = fetch_tools()

    if not tools:
        print("No tools found. Is the daemon running?", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(tools)} tools")

    # Generate the static file
    content = generate_static_file(tools)

    # Write to tools_static.py
    static_path = Path(__file__).parent / "tools_static.py"
    static_path.write_text(content)

    print(f"Written to {static_path}")
    print("Restart Claude Code to pick up new tools")


if __name__ == "__main__":
    sync()
