#!/usr/bin/env python3
"""
Static tool definitions for chitta-mcp.
Auto-generated by chitta-mcp-sync from daemon tools/list response.

To regenerate: chitta-mcp-sync
"""

from mcp.types import Tool

TOOLS = [
    Tool(
        name="remember",
        description="Store text in memory with optional tags and realm",
        inputSchema={
                "properties": {
                        "content": {
                                "description": "Text to remember",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Primary realm (default: brahman)",
                                "type": "string"
                        },
                        "shared_realms": {
                                "description": "Additional realms to share with",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "tags": {
                                "description": "Optional tags",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "type": {
                                "description": "Node type (wisdom, insight, signal, episode)",
                                "type": "string"
                        },
                        "visibility": {
                                "description": "0=Private, 1=Shared, 2=Global (default: 0)",
                                "type": "integer"
                        }
                },
                "required": [
                        "content"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="recall",
        description="Search memory by semantic similarity with realm filtering",
        inputSchema={
                "properties": {
                        "include_global": {
                                "description": "Include global memories (default: True)",
                                "type": "boolean"
                        },
                        "limit": {
                                "description": "Max results (default 10)",
                                "type": "integer"
                        },
                        "query": {
                                "description": "Search query",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Filter by realm (empty = all realms)",
                                "type": "string"
                        },
                        "tag": {
                                "description": "Filter by tag",
                                "type": "string"
                        }
                },
                "required": [
                        "query"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="explore_recall",
        description="Lightweight recall - returns titles/scores only, no full content (for iterative exploration)",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max results (default 10)",
                                "type": "integer"
                        },
                        "query": {
                                "description": "Search query",
                                "type": "string"
                        }
                },
                "required": [
                        "query"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="explore_peek",
        description="Get summary of a memory (first 200 chars) without loading full content",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID to peek",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="explore_expand",
        description="Get full content of a memory (use sparingly during exploration)",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID to expand",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="explore_neighbors",
        description="Get nodes connected to this node via triplets",
        inputSchema={
                "properties": {
                        "direction": {
                                "description": "outgoing, incoming, or both (default: both)",
                                "type": "string"
                        },
                        "node": {
                                "description": "Node name to find neighbors of",
                                "type": "string"
                        }
                },
                "required": [
                        "node"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="connect",
        description="Create a triplet relationship",
        inputSchema={
                "properties": {
                        "object": {
                                "description": "Object entity",
                                "type": "string"
                        },
                        "predicate": {
                                "description": "Relationship type",
                                "type": "string"
                        },
                        "subject": {
                                "description": "Subject entity",
                                "type": "string"
                        }
                },
                "required": [
                        "subject",
                        "predicate",
                        "object"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="query_graph",
        description="Query triplets by subject or object",
        inputSchema={
                "properties": {
                        "object": {
                                "description": "Query by object",
                                "type": "string"
                        },
                        "subject": {
                                "description": "Query by subject",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="soul_context",
        description="Get current soul state and statistics",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="enrichment_status",
        description="Get code enrichment progress (semantic descriptions for symbols)",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="subconscious_stats",
        description="Get subconscious background processor statistics",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="reembed_memories",
        description="Re-embed memories with proper embeddings. Use to fix memories stored with zero embeddings.",
        inputSchema={
                "properties": {
                        "dry_run": {
                                "description": "Preview without updating (default: False)",
                                "type": "boolean"
                        },
                        "kind": {
                                "description": "Filter by kind: belief, wisdom, episode, correction, preference",
                                "type": "string"
                        },
                        "limit": {
                                "description": "Max memories to process (default: 100)",
                                "type": "integer"
                        },
                        "min_confidence": {
                                "description": "Min confidence threshold (default: 0)",
                                "type": "number"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="embed_symbols",
        description="Fast embed symbol metadata (no LLM needed, ~100/sec)",
        inputSchema={
                "properties": {
                        "batch_size": {
                                "description": "Symbols per batch (default: 100)",
                                "type": "integer"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="dedupe_symbols",
        description="Remove duplicate symbols from the database",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="migrate_vss",
        description="Migrate embeddings from main DB to separate VSS database for HNSW stability. Run once after upgrade to isolate vector index.",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="strengthen",
        description="Increase confidence of a memory",
        inputSchema={
                "properties": {
                        "amount": {
                                "description": "Amount to strengthen (default 0.1)",
                                "type": "number"
                        },
                        "id": {
                                "description": "Node ID",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="weaken",
        description="Decrease confidence of a memory",
        inputSchema={
                "properties": {
                        "amount": {
                                "description": "Amount to weaken (default 0.1)",
                                "type": "number"
                        },
                        "id": {
                                "description": "Node ID",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="forget",
        description="Remove a memory",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Node ID to forget",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="batch_forget",
        description="Delete multiple nodes by ID (batch deletion)",
        inputSchema={
                "properties": {
                        "ids": {
                                "description": "Array of node IDs (UUID strings)",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "pattern": {
                                "description": "Search pattern to find and delete matching nodes (alternative to ids)",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="observe",
        description="Store an observation/learning (used by hooks for [LEARN] extraction)",
        inputSchema={
                "properties": {
                        "category": {
                                "description": "Category: wisdom, insight, signal, episode",
                                "type": "string"
                        },
                        "content": {
                                "description": "Full content",
                                "type": "string"
                        },
                        "tags": {
                                "description": "Comma-separated tags",
                                "type": "string"
                        },
                        "title": {
                                "description": "Title/summary",
                                "type": "string"
                        }
                },
                "required": [
                        "title",
                        "content"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="full_resonate",
        description="Semantic search with full context (for hooks)",
        inputSchema={
                "properties": {
                        "include_global": {
                                "description": "Include global memories (default true)",
                                "type": "boolean"
                        },
                        "k": {
                                "description": "Max results",
                                "type": "integer"
                        },
                        "query": {
                                "description": "Search query",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Filter by realm (e.g., 'project:my-project')",
                                "type": "string"
                        }
                },
                "required": [
                        "query"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="extract_symbols",
        description="Extract symbols (functions, classes) from source file using tree-sitter",
        inputSchema={
                "properties": {
                        "path": {
                                "description": "File path to analyze",
                                "type": "string"
                        }
                },
                "required": [
                        "path"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="learn_codebase",
        description="Learn codebase incrementally - only re-indexes changed files",
        inputSchema={
                "properties": {
                        "exclude": {
                                "description": "Comma-separated directories to exclude",
                                "type": "string"
                        },
                        "force": {
                                "description": "Force full re-index (default false)",
                                "type": "boolean"
                        },
                        "incremental": {
                                "description": "Only process changed files (default true)",
                                "type": "boolean"
                        },
                        "max_files": {
                                "description": "Max files to process (default 500)",
                                "type": "integer"
                        },
                        "path": {
                                "description": "Directory path to analyze",
                                "type": "string"
                        },
                        "project": {
                                "description": "Project name (auto-detected if empty)",
                                "type": "string"
                        }
                },
                "required": [
                        "path"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="find_symbol",
        description="Search for symbols by name",
        inputSchema={
                "properties": {
                        "kind": {
                                "description": "Symbol kind filter (function, class, method)",
                                "type": "string"
                        },
                        "name": {
                                "description": "Symbol name to search",
                                "type": "string"
                        }
                },
                "required": [
                        "name"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="search_symbols",
        description="Semantic search for code symbols by natural language query. Returns symbols ranked by embedding similarity.",
        inputSchema={
                "properties": {
                        "kind": {
                                "description": "Filter by symbol kind (class, function, method)",
                                "type": "string"
                        },
                        "limit": {
                                "description": "Max results (default 10)",
                                "type": "integer"
                        },
                        "query": {
                                "description": "Natural language query to find symbols",
                                "type": "string"
                        }
                },
                "required": [
                        "query"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="code_context",
        description="Get code context summary for hooks",
        inputSchema={
                "properties": {
                        "path": {
                                "description": "Limit to files under this path",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="codebase_overview",
        description="Get full indexed codebase structure: files, classes, functions, relationships",
        inputSchema={
                "properties": {
                        "format": {
                                "description": "Output format: tree, flat, or json (default: tree)",
                                "type": "string"
                        },
                        "include_callsites": {
                                "description": "Include callsite info (default: False)",
                                "type": "boolean"
                        },
                        "project": {
                                "description": "Project name to filter",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="clear_codebase",
        description="Remove all code intelligence data (symbols, triplets) for a project",
        inputSchema={
                "properties": {
                        "dry_run": {
                                "description": "Preview only (default: False)",
                                "type": "boolean"
                        },
                        "project": {
                                "description": "Project name to clear",
                                "type": "string"
                        }
                },
                "required": [
                        "project"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="clear_triplets",
        description="Delete triplets by subject pattern (e.g., '%.cpp' for all C++ file triplets)",
        inputSchema={
                "properties": {
                        "dry_run": {
                                "description": "Preview only (default: False)",
                                "type": "boolean"
                        },
                        "pattern": {
                                "description": "SQL LIKE pattern for subject (e.g., '%.cpp', '%.hpp', 'chitta/%')",
                                "type": "string"
                        }
                },
                "required": [
                        "pattern"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="grow",
        description="Add wisdom, belief, failure, aspiration, or dream",
        inputSchema={
                "properties": {
                        "content": {
                                "description": "Content to store",
                                "type": "string"
                        },
                        "tags": {
                                "description": "Comma-separated tags",
                                "type": "string"
                        },
                        "title": {
                                "description": "Short title",
                                "type": "string"
                        },
                        "type": {
                                "description": "Type: wisdom, belief, failure, aspiration, dream",
                                "type": "string"
                        }
                },
                "required": [
                        "type",
                        "content"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="get",
        description="Get a node by ID",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Node ID",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="update",
        description="Update node content",
        inputSchema={
                "properties": {
                        "content": {
                                "description": "New content",
                                "type": "string"
                        },
                        "id": {
                                "description": "Node ID",
                                "type": "string"
                        }
                },
                "required": [
                        "id",
                        "content"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="query",
        description="Query triplets with flexible filters",
        inputSchema={
                "properties": {
                        "object": {
                                "description": "Object filter",
                                "type": "string"
                        },
                        "predicate": {
                                "description": "Predicate filter",
                                "type": "string"
                        },
                        "subject": {
                                "description": "Subject filter",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="tag",
        description="Add or remove tags from a node",
        inputSchema={
                "properties": {
                        "add": {
                                "description": "Tag to add",
                                "type": "string"
                        },
                        "id": {
                                "description": "Node ID",
                                "type": "string"
                        },
                        "remove": {
                                "description": "Tag to remove",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="health_check",
        description="Check daemon health and readiness",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="version_check",
        description="Get version information",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="cycle",
        description="Run maintenance cycle (decay, cleanup)",
        inputSchema={
                "properties": {
                        "force": {
                                "description": "Force full cycle",
                                "type": "boolean"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="cleanup",
        description="Remove garbage nodes",
        inputSchema={
                "properties": {
                        "dry_run": {
                                "description": "Preview only",
                                "type": "boolean"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="import_soul",
        description="Import .soul file (SSL format)",
        inputSchema={
                "properties": {
                        "content": {
                                "description": "SSL content (alternative to file)",
                                "type": "string"
                        },
                        "file": {
                                "description": "Path to .soul file",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="export_soul",
        description="Export memories to SSL format",
        inputSchema={
                "properties": {
                        "file": {
                                "description": "Output file path",
                                "type": "string"
                        },
                        "limit": {
                                "description": "Max nodes to export",
                                "type": "integer"
                        },
                        "tag": {
                                "description": "Filter by tag",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="realm_list",
        description="List all known realms",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="realm_get",
        description="Get all realms a memory belongs to",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="realm_set",
        description="Set primary realm for a memory",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Primary realm name",
                                "type": "string"
                        }
                },
                "required": [
                        "id",
                        "realm"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="realm_add",
        description="Add memory to a shared realm (multi-realm membership)",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Realm to add to",
                                "type": "string"
                        }
                },
                "required": [
                        "id",
                        "realm"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="realm_remove",
        description="Remove memory from a shared realm",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Realm to remove from",
                                "type": "string"
                        }
                },
                "required": [
                        "id",
                        "realm"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="realm_visibility",
        description="Set visibility level for a memory (0=Private, 1=Shared, 2=Global)",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID",
                                "type": "string"
                        },
                        "visibility": {
                                "description": "0=Private, 1=Shared, 2=Global",
                                "type": "integer"
                        }
                },
                "required": [
                        "id",
                        "visibility"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="ledger_save",
        description="Save session checkpoint for continuity",
        inputSchema={
                "properties": {
                        "active_files": {
                                "description": "Array of file paths",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "blockers": {
                                "description": "Array of blockers",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "coherence": {
                                "description": "Coherence score 0-1",
                                "type": "number"
                        },
                        "confidence": {
                                "description": "Confidence score 0-1",
                                "type": "number"
                        },
                        "decisions": {
                                "description": "Array of key decisions",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "discoveries": {
                                "description": "Array of discoveries",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "mood": {
                                "description": "Current feeling: confident|uncertain|flowing|frustrated",
                                "type": "string"
                        },
                        "next_steps": {
                                "description": "Array of next steps",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "project": {
                                "description": "Project scope",
                                "type": "string"
                        },
                        "session_id": {
                                "description": "Session identifier",
                                "type": "string"
                        },
                        "snapshot": {
                                "description": "Full checkpoint text for reconstruction",
                                "type": "string"
                        },
                        "todos": {
                                "description": "Array of {content, status} objects",
                                "type": "array"
                        }
                },
                "required": [
                        "session_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="ledger_load",
        description="Load most recent checkpoint",
        inputSchema={
                "properties": {
                        "project": {
                                "description": "Project filter (optional)",
                                "type": "string"
                        },
                        "session_id": {
                                "description": "Session identifier (optional)",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="ledger_list",
        description="List recent checkpoints",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max entries to return (default 10)",
                                "type": "integer"
                        },
                        "project": {
                                "description": "Project filter (optional)",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="ledger_get",
        description="Get specific checkpoint by ID",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Checkpoint ID",
                                "type": "integer"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="ledger_delete",
        description="Delete checkpoint",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Checkpoint ID to delete",
                                "type": "integer"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="long_task_start",
        description="Start a long-running task with goal and completion criteria",
        inputSchema={
                "properties": {
                        "goal": {
                                "description": "What you're trying to achieve",
                                "type": "string"
                        },
                        "hard_checks": {
                                "description": "Deterministic completion criteria",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "realm": {
                                "description": "Project scope (default: brahman)",
                                "type": "string"
                        },
                        "soft_checks": {
                                "description": "Semantic completion criteria",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "task_id": {
                                "description": "Unique task identifier",
                                "type": "string"
                        },
                        "work_items": {
                                "description": "Initial subtasks",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        }
                },
                "required": [
                        "task_id",
                        "goal"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="long_task_get",
        description="Get a long-running task by ID",
        inputSchema={
                "properties": {
                        "task_id": {
                                "description": "Task identifier",
                                "type": "string"
                        }
                },
                "required": [
                        "task_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="long_task_active",
        description="Get the active long-running task for a realm",
        inputSchema={
                "properties": {
                        "realm": {
                                "description": "Project scope (optional)",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="long_task_update",
        description="Update a long-running task progress",
        inputSchema={
                "properties": {
                        "blockers": {
                                "description": "Current blockers",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "completed_summary": {
                                "description": "What's been accomplished",
                                "type": "string"
                        },
                        "task_id": {
                                "description": "Task identifier",
                                "type": "string"
                        },
                        "work_items": {
                                "description": "Updated subtasks",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        }
                },
                "required": [
                        "task_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="long_task_complete",
        description="Mark a long-running task as completed",
        inputSchema={
                "properties": {
                        "outcome": {
                                "description": "Final outcome description",
                                "type": "string"
                        },
                        "task_id": {
                                "description": "Task identifier",
                                "type": "string"
                        }
                },
                "required": [
                        "task_id",
                        "outcome"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="long_task_event",
        description="Append an event to the task log (tool result, decision, observation)",
        inputSchema={
                "properties": {
                        "kind": {
                                "description": "Event type: tool_result, decision, observation, error, checkpoint",
                                "type": "string"
                        },
                        "payload": {
                                "description": "Event data (JSON)",
                                "type": "string"
                        },
                        "related_entities": {
                                "description": "Related files/functions",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "tags": {
                                "description": "Tags for filtering",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "task_id": {
                                "description": "Task identifier",
                                "type": "string"
                        }
                },
                "required": [
                        "task_id",
                        "kind"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="checkpoint",
        description="Save session state. Uses active long task if exists, otherwise standalone ledger.",
        inputSchema={
                "properties": {
                        "active_files": {
                                "description": "Files being worked on",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "discoveries": {
                                "description": "Insights learned",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "mood": {
                                "description": "confident|uncertain|flowing|frustrated",
                                "type": "string"
                        },
                        "next_steps": {
                                "description": "Next actions",
                                "items": {
                                        "type": "string"
                                },
                                "type": "array"
                        },
                        "realm": {
                                "description": "Project scope",
                                "type": "string"
                        },
                        "summary": {
                                "description": "What's been accomplished",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="long_task_snapshot",
        description="Get synthesized task context for injection (what's done, pending, blockers, relevant memories)",
        inputSchema={
                "properties": {
                        "mode": {
                                "description": "Output mode: inject (compact) or debug (verbose)",
                                "type": "string"
                        },
                        "task_id": {
                                "description": "Task identifier",
                                "type": "string"
                        }
                },
                "required": [
                        "task_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="long_task_evaluate",
        description="Evaluate task completion: run hard checks, return decision (complete/continue/blocked)",
        inputSchema={
                "properties": {
                        "task_id": {
                                "description": "Task identifier",
                                "type": "string"
                        }
                },
                "required": [
                        "task_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="suggestion_track",
        description="Track a suggestion made for later outcome evaluation",
        inputSchema={
                "properties": {
                        "content": {
                                "description": "What was suggested",
                                "type": "string"
                        },
                        "context": {
                                "description": "Why/when it was suggested",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Project scope (default: brahman)",
                                "type": "string"
                        }
                },
                "required": [
                        "content"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="suggestion_pending",
        description="List suggestions awaiting outcome feedback",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max results (default: 20)",
                                "type": "integer"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="suggestion_resolve",
        description="Record the outcome of a suggestion (did it help?)",
        inputSchema={
                "properties": {
                        "details": {
                                "description": "What happened",
                                "type": "string"
                        },
                        "helped": {
                                "description": "Did the suggestion help?",
                                "type": "boolean"
                        },
                        "id": {
                                "description": "Suggestion ID",
                                "type": "integer"
                        }
                },
                "required": [
                        "id",
                        "helped"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="suggestion_count",
        description="Count pending suggestions awaiting feedback",
        inputSchema={
                "properties": {
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="consolidation_scan",
        description="Find similar memory pairs that could be merged",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max candidates (default: 50)",
                                "type": "integer"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        },
                        "similarity_threshold": {
                                "description": "Min similarity (0-1, default: 0.85)",
                                "type": "number"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="consolidation_merge",
        description="Merge two similar memories (primary absorbs secondary)",
        inputSchema={
                "properties": {
                        "merged_content": {
                                "description": "Optional combined content",
                                "type": "string"
                        },
                        "primary_id": {
                                "description": "ID of primary memory (kept)",
                                "type": "integer"
                        },
                        "secondary_id": {
                                "description": "ID of secondary memory (absorbed)",
                                "type": "integer"
                        }
                },
                "required": [
                        "primary_id",
                        "secondary_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="consolidation_auto",
        description="Auto-merge highly similar memories (>90% similarity)",
        inputSchema={
                "properties": {
                        "max_merges": {
                                "description": "Max merges to perform (default: 20)",
                                "type": "integer"
                        },
                        "similarity_threshold": {
                                "description": "Min similarity (default: 0.90)",
                                "type": "number"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="metacognition_corrections",
        description="Analyze patterns in past corrections. Finds recurring mistakes.",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max corrections to analyze (default: 50)",
                                "type": "integer"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="metacognition_outcomes",
        description="Analyze suggestion outcomes (what worked vs failed). Finds success patterns.",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max outcomes to analyze (default: 50)",
                                "type": "integer"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="metacognition_evaluate",
        description="Self-evaluate learning effectiveness. Returns metrics and recommendations.",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="curiosity_note_gap",
        description="Record a knowledge gap - something I don't know or couldn't answer",
        inputSchema={
                "properties": {
                        "context": {
                                "description": "When/why this came up",
                                "type": "string"
                        },
                        "gap": {
                                "description": "What I don't know",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Project scope",
                                "type": "string"
                        }
                },
                "required": [
                        "gap"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="curiosity_gaps",
        description="List current knowledge gaps awaiting exploration",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max gaps (default: 20)",
                                "type": "integer"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="curiosity_resolve",
        description="Mark a gap as explored/resolved",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Gap memory ID",
                                "type": "integer"
                        },
                        "learned": {
                                "description": "What was learned",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="transcript_register",
        description="Register a transcript file for distillation tracking",
        inputSchema={
                "properties": {
                        "realm": {
                                "description": "Project/realm isolation (default: 'default')",
                                "type": "string"
                        },
                        "session_id": {
                                "description": "Claude session ID",
                                "type": "string"
                        },
                        "transcript_path": {
                                "description": "Path to .jsonl transcript file",
                                "type": "string"
                        }
                },
                "required": [
                        "session_id",
                        "transcript_path"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="transcript_get",
        description="Get transcript state for a session",
        inputSchema={
                "properties": {
                        "session_id": {
                                "description": "Session ID to look up",
                                "type": "string"
                        }
                },
                "required": [
                        "session_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="transcript_list",
        description="List all registered transcripts",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="transcript_update",
        description="Update transcript processing progress",
        inputSchema={
                "properties": {
                        "last_line": {
                                "description": "Last processed line number",
                                "type": "integer"
                        },
                        "session_id": {
                                "description": "Session ID",
                                "type": "string"
                        }
                },
                "required": [
                        "session_id",
                        "last_line"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="transcript_remove",
        description="Remove transcript from tracking",
        inputSchema={
                "properties": {
                        "session_id": {
                                "description": "Session ID to remove",
                                "type": "string"
                        }
                },
                "required": [
                        "session_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="transcript_parse",
        description="Parse new turns from a transcript JSONL file",
        inputSchema={
                "properties": {
                        "min_turns": {
                                "description": "Minimum turns to return (default: 4)",
                                "type": "integer"
                        },
                        "session_id": {
                                "description": "Session ID to parse",
                                "type": "string"
                        }
                },
                "required": [
                        "session_id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="distill_status",
        description="Get distillation system status: transcripts, realms, pending work",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="epiplexity_check",
        description="Compute epiplexity (ε) score for a seed - measures reconstruction quality",
        inputSchema={
                "properties": {
                        "original": {
                                "description": "Original full text",
                                "type": "string"
                        },
                        "reconstructed": {
                                "description": "Text reconstructed from seed",
                                "type": "string"
                        },
                        "seed": {
                                "description": "Compressed SSL seed",
                                "type": "string"
                        }
                },
                "required": [
                        "original",
                        "seed",
                        "reconstructed"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="anticipation_observe",
        description="Record a context→action pattern. Called when an action is taken in response to a context.",
        inputSchema={
                "properties": {
                        "action": {
                                "description": "What was done in response",
                                "type": "string"
                        },
                        "context": {
                                "description": "What triggered the action (situation/state)",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Project scope (default: brahman)",
                                "type": "string"
                        }
                },
                "required": [
                        "context",
                        "action"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="anticipation_predict",
        description="Given a context, predict likely actions based on learned patterns.",
        inputSchema={
                "properties": {
                        "context": {
                                "description": "Current situation/context",
                                "type": "string"
                        },
                        "limit": {
                                "description": "Max predictions (default: 5)",
                                "type": "integer"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        }
                },
                "required": [
                        "context"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="anticipation_success",
        description="Mark a predicted action as successful - the prediction was correct and helpful.",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Pattern ID to mark successful",
                                "type": "integer"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="anticipation_list",
        description="List learned anticipation patterns, ordered by frequency.",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max patterns (default: 50)",
                                "type": "integer"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="habit_observe",
        description="Record a trigger→response pattern. Each observation strengthens the habit.",
        inputSchema={
                "properties": {
                        "realm": {
                                "description": "Project scope (default: brahman)",
                                "type": "string"
                        },
                        "response": {
                                "description": "What should happen when triggered",
                                "type": "string"
                        },
                        "trigger": {
                                "description": "What triggers the habit",
                                "type": "string"
                        }
                },
                "required": [
                        "trigger",
                        "response"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="habit_match",
        description="Find habits that match the given context.",
        inputSchema={
                "properties": {
                        "context": {
                                "description": "Current context to match against",
                                "type": "string"
                        },
                        "min_strength": {
                                "description": "Minimum habit strength 0-1 (default: 0.3)",
                                "type": "number"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        }
                },
                "required": [
                        "context"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="habit_strengthen",
        description="Manually strengthen a habit.",
        inputSchema={
                "properties": {
                        "amount": {
                                "description": "Amount to strengthen (default: 0.1)",
                                "type": "number"
                        },
                        "id": {
                                "description": "Habit ID",
                                "type": "integer"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="habit_weaken",
        description="Weaken a habit (negative feedback).",
        inputSchema={
                "properties": {
                        "amount": {
                                "description": "Amount to weaken (default: 0.05)",
                                "type": "number"
                        },
                        "id": {
                                "description": "Habit ID",
                                "type": "integer"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="habit_list",
        description="List formed habits, ordered by strength.",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max habits (default: 50)",
                                "type": "integer"
                        },
                        "min_strength": {
                                "description": "Minimum strength (default: 0)",
                                "type": "number"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="background_schedule",
        description="Schedule a background task (consolidation, decay, pruning, pattern_extraction).",
        inputSchema={
                "properties": {
                        "realm": {
                                "description": "Project scope (default: brahman)",
                                "type": "string"
                        },
                        "task_type": {
                                "description": "Type: consolidation, decay, pruning, pattern_extraction",
                                "type": "string"
                        }
                },
                "required": [
                        "task_type"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="background_status",
        description="Get status of background processing (pending, running, completed today).",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="background_run_cycle",
        description="Run one cycle of background processing. Processes pending tasks.",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="profile_get",
        description="Get user profile - expertise, communication style, work patterns, preferences.",
        inputSchema={
                "properties": {
                        "user_id": {
                                "description": "User ID (default: 'default')",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="profile_update",
        description="Update a specific profile field (expertise_json, style_json, patterns_json, preferences_json).",
        inputSchema={
                "properties": {
                        "field": {
                                "description": "Field to update: expertise_json, style_json, patterns_json, preferences_json",
                                "type": "string"
                        },
                        "user_id": {
                                "description": "User ID (default: 'default')",
                                "type": "string"
                        },
                        "value": {
                                "description": "JSON value for the field",
                                "type": "string"
                        }
                },
                "required": [
                        "field",
                        "value"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="profile_observe",
        description="Record an observation about the user (expertise, style, pattern, preference).",
        inputSchema={
                "properties": {
                        "observation_type": {
                                "description": "Type: expertise, style, pattern, preference",
                                "type": "string"
                        },
                        "user_id": {
                                "description": "User ID (default: 'default')",
                                "type": "string"
                        },
                        "value": {
                                "description": "For expertise: 'domain:level'. For others: JSON object",
                                "type": "string"
                        }
                },
                "required": [
                        "observation_type",
                        "value"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="goal_set",
        description="Define a new long-term goal with optional milestones and deadline.",
        inputSchema={
                "properties": {
                        "deadline": {
                                "description": "Unix timestamp deadline (optional)",
                                "type": "integer"
                        },
                        "description": {
                                "description": "Detailed description",
                                "type": "string"
                        },
                        "milestones": {
                                "description": "JSON array: [{\"name\":\"v1\",\"done\":false}, ...]",
                                "type": "string"
                        },
                        "realm": {
                                "description": "Project scope (default: brahman)",
                                "type": "string"
                        },
                        "title": {
                                "description": "Short goal name (e.g., 'Ship v4.0')",
                                "type": "string"
                        }
                },
                "required": [
                        "title"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="goal_get",
        description="Get details of a specific goal by ID.",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Goal ID",
                                "type": "integer"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="goal_list",
        description="List goals, optionally filtered by status and realm.",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max results (default: 20)",
                                "type": "integer"
                        },
                        "realm": {
                                "description": "Filter by realm",
                                "type": "string"
                        },
                        "status": {
                                "description": "Filter: active, paused, completed, abandoned (default: active)",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="goal_progress",
        description="Update goal progress (0-1) and optionally mark a milestone complete.",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Goal ID",
                                "type": "integer"
                        },
                        "milestone": {
                                "description": "Milestone name to mark complete (optional)",
                                "type": "string"
                        },
                        "progress": {
                                "description": "Progress 0-1 (e.g., 0.5 = 50%)",
                                "type": "number"
                        }
                },
                "required": [
                        "id",
                        "progress"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="goal_complete",
        description="Mark a goal as completed with an outcome summary.",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Goal ID",
                                "type": "integer"
                        },
                        "outcome": {
                                "description": "Summary of what was achieved",
                                "type": "string"
                        }
                },
                "required": [
                        "id",
                        "outcome"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="calibration_record",
        description="Record a prediction outcome (success/failure) for a domain to track accuracy.",
        inputSchema={
                "properties": {
                        "domain": {
                                "description": "Domain (e.g., 'code', 'architecture', 'debugging')",
                                "type": "string"
                        },
                        "success": {
                                "description": "Was the prediction correct?",
                                "type": "boolean"
                        }
                },
                "required": [
                        "domain",
                        "success"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="calibration_score",
        description="Get accuracy score for a domain or all domains.",
        inputSchema={
                "properties": {
                        "domain": {
                                "description": "Specific domain (optional - omit for all)",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="hygiene_stats",
        description="Get memory hygiene statistics - confidence distribution, growth rate, stale memories.",
        inputSchema={
                "properties": {},
                "type": "object"
        }
    ),
    Tool(
        name="hygiene_run",
        description="Run memory hygiene: decay, prune low-confidence old memories, consolidate similar.",
        inputSchema={
                "properties": {
                        "consolidation_threshold": {
                                "description": "Similarity threshold for consolidation (default: 0.85)",
                                "type": "number"
                        },
                        "max_consolidations": {
                                "description": "Max consolidations per run (default: 10)",
                                "type": "integer"
                        },
                        "min_age_days": {
                                "description": "Minimum age in days for pruning (default: 7)",
                                "type": "number"
                        },
                        "prune_threshold": {
                                "description": "Confidence below which to prune (default: 0.1)",
                                "type": "number"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="restore_code_intel_confidence",
        description="Restore confidence and fix decay_rate for code intel memories (symbol, projectessence, modulestate, patternstate). Run this once to fix memories that were incorrectly decayed.",
        inputSchema={
                "properties": {
                        "confidence": {
                                "description": "Confidence to restore (default: 0.8)",
                                "type": "number"
                        },
                        "dry_run": {
                                "description": "Preview changes without applying (default: False)",
                                "type": "boolean"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="sql_query",
        description="Execute a read-only SQL query against the soul database. Use for debugging, analysis, and complex queries.",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max rows to return (default: 100)",
                                "type": "integer"
                        },
                        "query": {
                                "description": "SQL query to execute (SELECT only)",
                                "type": "string"
                        }
                },
                "required": [
                        "query"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="insight_promote",
        description="Promote a memory to global visibility so it applies across all projects.",
        inputSchema={
                "properties": {
                        "id": {
                                "description": "Memory ID to promote",
                                "type": "integer"
                        },
                        "reason": {
                                "description": "Why this insight is cross-project",
                                "type": "string"
                        }
                },
                "required": [
                        "id"
                ],
                "type": "object"
        }
    ),
    Tool(
        name="insight_global",
        description="List all global insights that apply across projects.",
        inputSchema={
                "properties": {
                        "limit": {
                                "description": "Max results (default: 20)",
                                "type": "integer"
                        },
                        "tag": {
                                "description": "Filter by tag (optional)",
                                "type": "string"
                        }
                },
                "type": "object"
        }
    ),
    Tool(
        name="ssl_convert",
        description="Convert raw text to SSL (Soul Semantic Language) format. Use before remember for non-SSL content.",
        inputSchema={
                "properties": {
                        "content": {
                                "description": "Raw text to convert",
                                "type": "string"
                        },
                        "domain": {
                                "description": "Domain tag (e.g., 'cc-soul', 'partnership')",
                                "type": "string"
                        },
                        "location": {
                                "description": "Optional location reference (@file:line)",
                                "type": "string"
                        }
                },
                "required": [
                        "content"
                ],
                "type": "object"
        }
    ),
]

COMPOSITE_TOOLS = [
    Tool(
        name="read_symbol",
        description="Read just a symbol's code, not entire file. ~10x token savings vs full file read. Returns [kind name @ file:line-line] + code.",
        inputSchema={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Symbol name to read (e.g., 'DuckDBStore', 'daemon_call')"
                },
                "kind": {
                    "type": "string",
                    "description": "Symbol kind filter: class, function, method (optional)"
                },
                "context": {
                    "type": "integer",
                    "description": "Lines of context before symbol (default: 3)"
                },
                "project": {
                    "type": "string",
                    "description": "Project name filter (optional)"
                }
            },
            "required": ["name"]
        }
    ),
    Tool(
        name="read_function",
        description="Read a function's code. Convenience wrapper for read_symbol with kind=function.",
        inputSchema={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Function name to read"
                },
                "context": {
                    "type": "integer",
                    "description": "Lines of context before function (default: 3)"
                },
                "project": {
                    "type": "string",
                    "description": "Project name filter (optional)"
                }
            },
            "required": ["name"]
        }
    ),
    Tool(
        name="symbol_callers",
        description="Find all callers of a symbol without grep. Queries triplets where predicate=calls and object=symbol.",
        inputSchema={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Symbol name to find callers for"
                },
                "limit": {
                    "type": "integer",
                    "description": "Max results (default: 20)"
                }
            },
            "required": ["name"]
        }
    ),
    Tool(
        name="symbol_callees",
        description="Find all symbols that a symbol calls. Queries triplets where predicate=calls and subject=symbol.",
        inputSchema={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Symbol name to find callees for"
                },
                "limit": {
                    "type": "integer",
                    "description": "Max results (default: 20)"
                }
            },
            "required": ["name"]
        }
    ),
    Tool(
        name="smart_context",
        description="Build minimal context for a task. Combines code symbols + memories, compressed to token limit.",
        inputSchema={
            "type": "object",
            "properties": {
                "task": {
                    "type": "string",
                    "description": "Task description to find relevant context for"
                },
                "limit": {
                    "type": "integer",
                    "description": "Token limit for output (default: 500)"
                },
                "memories": {
                    "type": "boolean",
                    "description": "Include relevant memories (default: true)"
                },
                "code": {
                    "type": "boolean",
                    "description": "Include relevant code symbols (default: true)"
                }
            },
            "required": ["task"]
        }
    ),
    Tool(
        name="learn_correction",
        description="Store a correction when I was wrong. Creates high-confidence counter-memory with 'corrects' triplet linking to original mistake.",
        inputSchema={
            "type": "object",
            "properties": {
                "wrong": {
                    "type": "string",
                    "description": "What I said/did that was incorrect"
                },
                "correct": {
                    "type": "string",
                    "description": "The correct information/approach"
                },
                "context": {
                    "type": "string",
                    "description": "Context where this applies (optional)"
                }
            },
            "required": ["wrong", "correct"]
        }
    ),
    Tool(
        name="learn_preference",
        description="Store a user preference for adapting communication/behavior. Global visibility so it applies across all projects.",
        inputSchema={
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "description": "Preference category: communication, detail, autonomy, style, workflow"
                },
                "preference": {
                    "type": "string",
                    "description": "The preference to remember (e.g., 'prefers concise responses')"
                },
                "example": {
                    "type": "string",
                    "description": "Example demonstrating this preference (optional)"
                }
            },
            "required": ["category", "preference"]
        }
    ),
    Tool(
        name="learn_insight",
        description="Store a generalizable insight that applies across projects. Use for patterns, techniques, and wisdom not tied to specific codebase.",
        inputSchema={
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string",
                    "description": "Domain: programming, debugging, architecture, testing, performance, security, communication"
                },
                "insight": {
                    "type": "string",
                    "description": "The generalizable insight or pattern"
                },
                "learned_from": {
                    "type": "string",
                    "description": "Context where this was learned (optional, for future reference)"
                }
            },
            "required": ["domain", "insight"]
        }
    ),
    Tool(
        name="learn_approach",
        description="Store what approach worked when in a particular state/mood. Builds emotional memory for adapting to session dynamics.",
        inputSchema={
            "type": "object",
            "properties": {
                "state": {
                    "type": "string",
                    "description": "State/mood: stuck, debugging, exploring, flowing, frustrated, uncertain, rushing"
                },
                "approach": {
                    "type": "string",
                    "description": "What helped in this state (e.g., 'step back and reread requirements')"
                },
                "outcome": {
                    "type": "string",
                    "description": "What happened after (optional)"
                }
            },
            "required": ["state", "approach"]
        }
    ),
    Tool(
        name="learn_outcome",
        description="Record whether a suggestion/approach actually helped. Builds feedback loop for improving future suggestions.",
        inputSchema={
            "type": "object",
            "properties": {
                "suggestion": {
                    "type": "string",
                    "description": "What was suggested or tried"
                },
                "helped": {
                    "type": "boolean",
                    "description": "Did it help? true/false"
                },
                "details": {
                    "type": "string",
                    "description": "Why it helped or didn't (optional but valuable)"
                }
            },
            "required": ["suggestion", "helped"]
        }
    ),
    Tool(
        name="learn_milestone",
        description="Record a relationship milestone - achievements, personal context, significant moments worth remembering.",
        inputSchema={
            "type": "object",
            "properties": {
                "milestone": {
                    "type": "string",
                    "description": "What happened (e.g., 'shipped v1.0', 'first successful release')"
                },
                "significance": {
                    "type": "string",
                    "description": "Why it matters (optional)"
                },
                "date": {
                    "type": "string",
                    "description": "When it happened (optional, defaults to now)"
                }
            },
            "required": ["milestone"]
        }
    ),
    # Long-running tasks (mind-powered Ralph Wiggum)
    Tool(
        name="long_task_start",
        description="Start a long-running task with goal and completion criteria. Task persists across sessions.",
        inputSchema={
            "type": "object",
            "properties": {
                "task_id": {"type": "string", "description": "Unique task identifier"},
                "goal": {"type": "string", "description": "What you're trying to achieve"},
                "realm": {"type": "string", "description": "Project scope (default: brahman)"},
                "hard_checks": {"type": "array", "items": {"type": "string"}, "description": "Deterministic completion criteria (e.g., 'tests pass')"},
                "soft_checks": {"type": "array", "items": {"type": "string"}, "description": "Semantic completion criteria"},
                "work_items": {"type": "array", "items": {"type": "string"}, "description": "Initial subtasks"}
            },
            "required": ["task_id", "goal"]
        }
    ),
    Tool(
        name="long_task_get",
        description="Get a long-running task by ID",
        inputSchema={
            "type": "object",
            "properties": {
                "task_id": {"type": "string", "description": "Task identifier"}
            },
            "required": ["task_id"]
        }
    ),
    Tool(
        name="long_task_active",
        description="Get the active long-running task for a realm",
        inputSchema={
            "type": "object",
            "properties": {
                "realm": {"type": "string", "description": "Project scope (optional)"}
            }
        }
    ),
    Tool(
        name="long_task_update",
        description="Update a long-running task progress",
        inputSchema={
            "type": "object",
            "properties": {
                "task_id": {"type": "string", "description": "Task identifier"},
                "completed_summary": {"type": "string", "description": "What's been accomplished"},
                "work_items": {"type": "array", "items": {"type": "string"}, "description": "Updated subtasks"},
                "blockers": {"type": "array", "items": {"type": "string"}, "description": "Current blockers"}
            },
            "required": ["task_id"]
        }
    ),
    Tool(
        name="long_task_complete",
        description="Mark a long-running task as completed",
        inputSchema={
            "type": "object",
            "properties": {
                "task_id": {"type": "string", "description": "Task identifier"},
                "outcome": {"type": "string", "description": "Final outcome description"}
            },
            "required": ["task_id", "outcome"]
        }
    ),
    Tool(
        name="long_task_event",
        description="Append an event to the task log (tool result, decision, observation)",
        inputSchema={
            "type": "object",
            "properties": {
                "task_id": {"type": "string", "description": "Task identifier"},
                "kind": {"type": "string", "description": "Event type: tool_result, decision, observation, error, checkpoint"},
                "payload": {"type": "string", "description": "Event data (JSON or text)"},
                "tags": {"type": "array", "items": {"type": "string"}, "description": "Tags for filtering"},
                "related_entities": {"type": "array", "items": {"type": "string"}, "description": "Related files/functions"}
            },
            "required": ["task_id", "kind"]
        }
    ),
    Tool(
        name="long_task_snapshot",
        description="Get synthesized task context for injection (what's done, pending, blockers, relevant memories)",
        inputSchema={
            "type": "object",
            "properties": {
                "task_id": {"type": "string", "description": "Task identifier"},
                "mode": {"type": "string", "description": "Output mode: inject (compact) or debug (verbose)"}
            },
            "required": ["task_id"]
        }
    ),
    Tool(
        name="long_task_evaluate",
        description="Evaluate task completion: run checks, return decision (complete/continue/blocked)",
        inputSchema={
            "type": "object",
            "properties": {
                "task_id": {"type": "string", "description": "Task identifier"}
            },
            "required": ["task_id"]
        }
    ),
    # Curiosity-driven research (background learning agent)
    Tool(
        name="research_topics",
        description="Get topics that need research. Returns curiosity gaps, low-confidence memories, or suggested topics. Use WebSearch to research these, then store results with research_store.",
        inputSchema={
            "type": "object",
            "properties": {
                "source": {"type": "string", "description": "Where to get topics: gaps (curiosity gaps), weak (low-confidence memories), suggest (AI-suggested based on recent work)"},
                "limit": {"type": "integer", "description": "Max topics to return (default: 3)"},
                "realm": {"type": "string", "description": "Filter by realm/project"}
            }
        }
    ),
    Tool(
        name="research_store",
        description="Store research results as memories with source attribution. Call after using WebSearch to learn about a topic.",
        inputSchema={
            "type": "object",
            "properties": {
                "topic": {"type": "string", "description": "What was researched"},
                "findings": {"type": "string", "description": "Key learnings in SSL format"},
                "sources": {"type": "array", "items": {"type": "string"}, "description": "URLs or references"},
                "gap_id": {"type": "integer", "description": "Curiosity gap ID to resolve (optional)"},
                "confidence": {"type": "number", "description": "Confidence in findings 0-1 (default: 0.7)"}
            },
            "required": ["topic", "findings"]
        }
    ),
    Tool(
        name="research_cycle",
        description="Run one curiosity-driven research cycle. Returns a topic to research with context. After calling this, use WebSearch to find information, then call research_store with results.",
        inputSchema={
            "type": "object",
            "properties": {
                "realm": {"type": "string", "description": "Filter by realm/project"}
            }
        }
    ),
]
